packages:
  - "apps/*"
  - "packages/*"
  - "tests/*"
  - "scripts/*"
  - "infrastructure/*"

onlyBuiltDependencies:
  - "@prisma/engines"
  - "esbuild"
  - "prisma"
  - "sharp"
allowBuilds:
  "@prisma/engines": true
  esbuild: true
  prisma: true
  sharp: true
