packages:
  - "apps/*"
  - "packages/*"
  - "packages/integrations/*/*"
  - "tests/*"
  - "scripts/*"
  - "infrastructure/*"

blockExoticSubdeps: false

onlyBuiltDependencies:
  - "@prisma/engines"
  - "@whiskeysockets/baileys"
  - "esbuild"
  - "prisma"
  - "protobufjs"
  - "sharp"
allowBuilds:
  "@prisma/engines": true
  "@whiskeysockets/baileys": true
  esbuild: true
  prisma: true
  protobufjs: true
  sharp: true
