ALTER TYPE "ProjectReportType" ADD VALUE IF NOT EXISTS 'MORNING_BRIEF';
ALTER TYPE "ProjectReportType" ADD VALUE IF NOT EXISTS 'DAILY_SUMMARY';
ALTER TYPE "ProjectReportType" ADD VALUE IF NOT EXISTS 'RISK_SUMMARY';
ALTER TYPE "ProjectReportType" ADD VALUE IF NOT EXISTS 'PENDING_DECISIONS';
